import Navbar from '@/components/navbar'
import { Inter } from 'next/font/google'
import SocialNavbar from './components/navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by  next js',
}

export default function socialLayout({ children }) {
  return (
    
      <div  className="h-[100%] overflow-scroll  fixed">  
      <Navbar title={"Be Social"}></Navbar>   
      <SocialNavbar></SocialNavbar>
       {children}
      </div>
    
  )
}
