import Sidebar from '@/components/sidebar'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by  next js',
}

export default function DashboardLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`bg-[#ececec] `}>
      <div className='flex'>
       <Sidebar></Sidebar>
       <div className='w-[100%] md:px-5'>       
        {children}
        </div>
      </div>
        </body>
    </html>
  )
}
